# DO NOT TOUCH THIS
CONFIG_VERSION: 2.0

# General Plugin Configuration
PREFIX: ""
SILENT_PERMISSION_CHECK: true
USE_COMMAND_CONFIRMATION: false

# Commands Configuration
# <> - Required
# [] - Optional
COMMANDS:
  # Global Chat Command (/globalchat|global|gc|g <message>)
  # Sends your message to the whole network
  GLOBALCHAT_COMMAND:
    COOLDOWN: 15
    LOGS_GLOBALCHAT_TO_CONSOLE: true

  # Hub Command (/hub)
  # Sends you to hub servers
  HUB_COMMAND:
    HUB_SERVERS:
      - hub
      - hub1
      - hub2